#!/bin/sh
WP_VERSION=1.0.0
WP=TPWeakProxy-${WP_VERSION}
WP_ZIP=${WP_VERSION}.zip

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

curl -L https://github.com/tetherpad/TPWeakProxy/archive/${WP_ZIP} > ${WP_ZIP}
rm -rf $WP
unzip ${WP_ZIP}
rm ${WP_ZIP}
